# Site wide configuration

title: "ANMA - ANxiety MAnager"
description: "A Feel Good App that help yous to win over your anxiety"
logo: anma_feelgood_logo.png
teaser: anma-feelgood.png
locale: en
url: https://anmafeelgood.github.io
#url: http://localhost:4000
#url: http://anmafeelgood.com
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: ANMA
  email: cyberbitgame2d@gmail.com
  twitter: anxiety_manager
  google:
    ad-client:
    ad-slot:
  bio: A feel good app that helps to reduce your anxiety level
  avatar: bio-photo.png
  disqus-shortname: anmafeelgood


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
